name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  NODE_VERSION: '20.x'

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Debug TypeScript setup
        run: |
          echo "TypeScript version:"
          npx tsc --version
          echo "Node modules @types:"
          ls -la node_modules/@types/ | head -20
          echo "Checking for minimatch types:"
          ls -la node_modules/@types/minimatch/ || echo "minimatch types not found"

      - name: Compile smart contracts
        run: npx hardhat compile

      - name: Check TypeScript compilation
        run: npm run build

      - name: Run Solidity linter (if available)
        run: |
          if npm list solhint > /dev/null 2>&1; then
            npx solhint 'contracts/**/*.sol'
          else
            echo "Solhint not installed, skipping Solidity linting"
          fi
        continue-on-error: true

  test:
    runs-on: ubuntu-latest
    needs: lint-and-format

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run all tests
        run: npx hardhat test --verbose

      - name: Run tests with gas reporting
        run: |
          if npm list hardhat-gas-reporter > /dev/null 2>&1; then
            REPORT_GAS=true npx hardhat test
          else
            echo "Gas reporter not configured, skipping gas reporting"
          fi
        continue-on-error: true

      - name: Generate test coverage
        run: npx hardhat coverage
        continue-on-error: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: matrix.node-version == '20.x'
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  security-check:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run security audit
        run: npm audit --audit-level moderate
        continue-on-error: true

      - name: Run Slither analysis (if available)
        run: |
          if command -v slither > /dev/null 2>&1; then
            slither . --exclude-dependencies
          else
            echo "Slither not installed, skipping static analysis"
          fi
        continue-on-error: true

  build-artifacts:
    runs-on: ubuntu-latest
    needs: [test, security-check]
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Compile contracts
        run: npx hardhat compile

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: contract-artifacts
          path: |
            artifacts/
            typechain-types/
          retention-days: 30
